### ISSUE TITLE
undefined is cast to string

### ISSUE THREAD

**Issue by Nautigsam** [litejs/natural-compare-lite#10]
If the function is given `undefined` it is [cast to String](https://github.com/litejs/natural-compare-lite/blob/master/index.js#L38). You expect an error to occur or something but instead you compare to the string `'undefined'`. That's a shame.

**Comment by lauriro** [comment]
It is a choice, I would rather accept non-ideal order than a broken application.

When data transformation or validation is needed (eg toLowerCase()),
you should perform your tasks before sorting.
Performing them inside a sort on every comparison can be slow.
