### ISSUE TITLE
Add License file

### ISSUE THREAD

**Issue by MarkAshraf96** [litejs/natural-compare-lite#13]
Including the license file, makes the packages compatible with license checkers and attribution file generators, that a lot of developers need for generating copyrights/attribution files.

I can easily create a PR with that change if you allow it.

**Comment by lauriro** [comment]
Could you point out some popular license checker that does not understand package.json?
I just try to understand the scale of the issue.

**Comment by MarkAshraf96** [comment]
For example this is what the "license-checker" tool get: 
![image](https://github.com/user-attachments/assets/08683f1d-7570-4750-a68d-b8cb9e1be1ae)
and although it can see the license "MIT" in the package.json it can't find the license file so it points to the readme, which is not useful if someone is trying to generate a copyrights/attribution file.
For example also the 'oss-attribution-generator' output will be missing the license text:
![image](https://github.com/user-attachments/assets/02763195-ac14-4a58-a75c-13b743a9d3b0)

As now the licensing and compliance work is getting more and more popular, it becoming more of a best practice to include the license file in the package also to comply with this restriction of the "MIT" license:

"_The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software._"
