### ISSUE TITLE
support sorting direction

### ISSUE THREAD

**Issue by yairEO** [litejs/natural-compare-lite#9]
ASC, DESC...

**Comment by lauriro** [comment]
natural-compare-lite is meant for using with native `array.sort()` method.

For sorting objects you need a wrapper anyway,
a direction can be defined there.

```javascript
// Use wrapper function for ASC
a.sort(function(a, b){
  return String.naturalCompare(a, b);
})
// Use wrapper function for DESC
a.sort(function(a, b){
  return String.naturalCompare(b, a);
})
```

**Comment by yairEO** [comment]
Yeah I figured as much after opening this issue.. 
Thanks for your well done work!
